name: AWS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_DEFAULT_OUTPUT: json
  AWS_PAGER: ""

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      # https://github.com/aws-actions/configure-aws-credentials#notice-node12-deprecation-warning
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: arn:aws:iam::426579533370:role/github_actions_image_retriever
          role-duration-seconds: 1800
          aws-region: us-east-2
          
      - name: Test authentication
        run: aws sts get-caller-identity

      - name: Run image download script
        run: ./get-aws-images.sh

      - name: Store image data in artifact
        uses: actions/upload-artifact@v3
        with:
          name: cloud-image-data
          path: "*.json.zst"