name: Parser

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

env:
  AWS_DEFAULT_OUTPUT: json
  AWS_PAGER: ""

jobs:
  parser:
    name: "🔎 Parse image data"
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v3"

      - name: Install awscli v2
        uses: unfor19/install-aws-cli-action@v1

      # https://github.com/aws-actions/configure-aws-credentials#notice-node12-deprecation-warning
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2.0.0
        with:
          role-to-assume: arn:aws:iam::426579533370:role/github_actions_image_retriever
          role-duration-seconds: 1800
          aws-region: us-east-2

      - name: Download logs from artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: retrieve.yml
          path: raw
          # Run it even if the retrieval failed.
          workflow_conclusion: completed

      - name: Install poetry
        run: pipx install poetry

      - name: Filter AWS data
        run: |
          mkdir -p filtered
          poetry install --no-dev
          poetry run filter-aws --input-path raw/aws --output-path filtered

      - name: Upload raw data to S3
        run: |
          aws s3 sync \
            --acl public-read \
            --delete \
            --content-type application/json \
            $(pwd)/raw/ s3://cloudx-json-bucket/raw/

      # Filtered data has no extension, so be sure to force the mime type here.
      - name: Upload filtered data to S3
        run: |
          aws s3 sync \
            --acl public-read \
            --delete \
            --content-type application/json \
            $(pwd)/filtered/ s3://cloudx-json-bucket/filtered/

      - name: Add region CSV data to repository
        run: |-
          git config user.name "Major Hayden"
          git config user.email "major@redhat.com"
          git add filtered/aws/region_csv/
          timestamp=$(date -u)
          git commit -m "Updating region CSV data: ${timestamp}" || exit 0
          # Sometimes there are leftover .pyc files.
          git clean -fxd
          git status
          git pull --rebase
          git push
