name: Parser

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

env:
  AWS_DEFAULT_OUTPUT: json
  AWS_PAGER: ""

jobs:
  parser:
    name: "🔎 Parse image data"
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v3"

      # https://github.com/aws-actions/configure-aws-credentials#notice-node12-deprecation-warning
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: arn:aws:iam::426579533370:role/github_actions_image_retriever
          role-duration-seconds: 1800
          aws-region: us-east-2

      - name: Download logs from artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: retrieve.yml
          path: raw
          # Run it even if the retrieval failed.
          workflow_conclusion: completed

      - name: Set up retriever
        run: |
          pipx install poetry
          poetry --directory=retriever install

      - name: Filter AWS data
        run: |
          mkdir -p data/aws
          poetry --directory=retriever run filter-aws --input-path raw/aws --output-path data/aws

      - name: Commit filtered data to repository
        uses: EndBug/add-and-commit@v9
        with:
          add: data
          author_name: "GitHub Actions"
          author_email: "noreply@imagedirectory.cloud"
          push: true

      - name: Upload to S3
        run: |
          pipx install s3cmd
          s3cmd sync --acl-public --delete-removed --guess-mime-type --no-mime-magic \
            $(pwd)/raw/ s3://cloudx-json-bucket/raw/
