name: Tester

on:
  workflow_dispatch:

permissions:
  actions: write

jobs:
  tester:
    name: "Test workflow dispatching"
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: "actions/checkout@v3"

      - name: Launch the parser workflow
        run: gh workflow run parse.yml
        env:
          GH_TOKEN: ${{ github.token }}
